

# image:
#   - Visual Studio 2017
#   - Ubuntu1804

platform: x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      nodejs_version: 8
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      nodejs_version: 9
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      nodejs_version: node

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: 8
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: 9
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      nodejs_version: Current

build: off

install:
 - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
 - ps: Update-AppveyorBuild -Version "$env:package_version.$env:APPVEYOR_BUILD_NUMBER"
 - cmd: powershell -command "Install-Product node $env:nodejs_version"
 - sh: nvm install $nodejs_version
 - npm install

test_script:
  - node --version
  - npm test

